---
- hosts: all
  become: yes
  user: vagrant
  tasks:
  - name: Install net-tools
    yum: name=net-tools state=installed

  - name: Install httpd
    yum: name=httpd state=installed

  - name: Start httpd
    service: name=httpd state=started enabled=yes

  - name: Start firewalld
    service: name=firewalld state=started enabled=yes

  - name: Set firewalld
    firewalld: zone=public service=http state=enabled permanent=true immediate=yes

  - name: Install Git
    yum: name=git state=installed

  - name: Install PHP
    yum: name=php state=installed

  - name: Install MariaDB
    yum: name=mariadb state=installed

  - name: Install MariaDB Server
    yum: name=mariadb-server state=installed

  - name: Start MariaDB
    service: name=mariadb state=started enabled=yes
